package olx;


/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * tt1.java
 *
 * Created on Nov 11, 2014, 10:38:45 AM
 */

/**
 *
 * @author Machine38
 */
import javax.swing.ImageIcon;
import javax.swing.ImageIcon.*;
import javax.swing.JOptionPane;

public class tt1 extends javax.swing.JFrame {

    /** Creates new form tt1 */
    public tt1() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cb1 = new javax.swing.JComboBox();
        l1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("jLabel1");

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18));
        jLabel4.setForeground(new java.awt.Color(0, 51, 204));
        jLabel4.setText("ITS OFFER TIME...!!!");

        cb1.setFont(new java.awt.Font("Tahoma", 1, 12));
        cb1.setForeground(new java.awt.Color(0, 51, 204));
        cb1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Offer 1", "Offer 2", "Offer 3", "Offer 4", "Offer 5", "Offer 6", "Offer 7", "Offer 8", "Offer 9", "Offer 10", " " }));
        cb1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cb1ActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jButton1.setForeground(new java.awt.Color(0, 51, 204));
        jButton1.setText("READY");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("CHOOSE NO. AT UNIT DIGIT OF YOUR CID");

        jButton2.setText("HOME");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(311, 311, 311)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(361, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(261, 261, 261)
                .addComponent(jLabel4)
                .addContainerGap(293, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(324, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(277, 277, 277)
                .addComponent(l1, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(108, 108, 108))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cb1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(35, 35, 35)
                .addComponent(jButton1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                        .addComponent(l1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jButton2)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cb1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cb1ActionPerformed
        // TODO add your handling code here:
}//GEN-LAST:event_cb1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
           String ff =(String)cb1.getSelectedItem();

           if(ff.equals("Offer 1"))
           { 
               l1.setIcon(new ImageIcon("C:\\shoppe\\mixer.jpg"));
          JOptionPane.showMessageDialog(null,"Congratulations,you have won a Mixer.");}
           else

           if(ff.equals("Offer 2")){
              
               l1.setIcon(new ImageIcon("C:\\shoppe\\2.jpg"));
         JOptionPane.showMessageDialog(null,"Congratulations,you have won a Sofa.");}
           else

           if(ff.equals("Offer 3"))
           {
               l1.setIcon(new ImageIcon("C:\\shoppe\\3.jpg"));
          JOptionPane.showMessageDialog(null,"Congratulations,you have won a Sewing Machine.");}
           else
           if(ff.equals("Offer 4")){
              l1.setIcon(new ImageIcon("C:\\shoppe\\4.jpg"));
           JOptionPane.showMessageDialog(null,"Congratulations,you have won a Printer.");}
           else
           if(ff.equals("Offer 5")){
              l1.setIcon(new ImageIcon("C:\\shoppe\\5.jpg"));
          JOptionPane.showMessageDialog(null,"Congratulations,you have won a Dining Table Set.");}
           else
           if(ff.equals("Offer 6")){
               l1.setIcon(new ImageIcon("C:\\shoppe\\6.jpg"));
          JOptionPane.showMessageDialog(null,"Congratulations,you have won a Microwave Oven.");}
           else
           if(ff.equals("Offer 7")){
               l1.setIcon(new ImageIcon("C:\\shoppe\\7.jpg"));
           JOptionPane.showMessageDialog(null,"Congratulations,you have won a LCD.");}
           else
           if(ff.equals("Offer 8")){
               l1.setIcon(new ImageIcon("C:\\shoppe\\8.jpg"));
           JOptionPane.showMessageDialog(null,"Congratulations,you have won a Tablet");}
           else
           if(ff.equals("Offer 9")){
             l1.setIcon(new ImageIcon("C:\\shoppe\\9.jpg"));
           JOptionPane.showMessageDialog(null,"Congratulations,you have won a Hair Accessories Kit.");}
           else
            if(ff.equals("Offer 10")){
              l1.setIcon(new ImageIcon("C:\\shoppe\\10.jpg"));
        JOptionPane.showMessageDialog(null,"Congratulations,you have won a Cell Phone.");}
           

    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
      OLX1 G=new OLX1();
      G.show(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tt1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox cb1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel l1;
    // End of variables declaration//GEN-END:variables

}
